print("Merhaba. Ben yeni bir chat programinin demo versiyonuyum. Adim Chat0.")
ad = input("Adin ne?:")
print("Tanistigimiza memnun oldum", ad)
durum = input("Nasilsin?")
print("Umarim daha iyi olursun.", ad)
dil = input("Anadilin disinda kac dil biliyorsun?")
print(dil, "Bu cok iyi. Kendini gelistirmeye devam etmelisin. Her lisan bir insan.")
mesgul = input("Su siralar ne ile mesgulsun?")
print(mesgul,"Senin ici oldukca onemli olmali.")
kitap = input("Gunluk kac sayfa kitap okursun?")
print(kitap,"Onemli olan sayfa sayisi degil. Surekli ve efektif okumak.")
yemek = input("En sevdigin yemek nedir?")
print("Kulaga oldukca lezzetli geliyor.")